# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170505_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 0, 7, 25, 771827, tzinfo=utc)),
        ),
    ]
