# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170505_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 0, 39, 35, 216446, tzinfo=utc)),
        ),
    ]
