# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170505_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 15, 6, 9, 617968, tzinfo=utc)),
        ),
    ]
